application:
  groups:
      - name: group1
        permissions:
          - subscriber
          - publisher
      - name: group2
        permissions:
          - subscriber
          - publisher
          - logging
          - monitoring
