groups:
  groups:
    - group1:
        permissions:
          - subscriber
          - publisher
    - group2:
        permissions:
          - subscriber
          - publisher
          - logging
          - monitoring
